sorcery:
  google_callback_url: 'https://qualificationtake.onrender.com/oauth/callback?provider=google'
  # google_callback_url: 'https://www.kyouzaichoice.com/oauth/callback?provider=google'

default_url_options:
  protcol: 'https'
  host: 'qualificationtake.onrender.com'
# host: 'www.kyouzaichoice.com'

