name: Run Rubocop

on:
  push:

jobs:
  rubocop:
    # ジョブが実行されるランナー(仮想デバイス)の種類
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Rubyをセットアップする
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop
